Repository vmware/terraform-provider-nsxt, pull requests merged in 2019-04, with the labels that each got.

#158 Updated the interop to be current with 2.4.
  README.md
Labels: size/XS

#157 Support for LogicalRouter FirewallSection and LogicalRouterPort Rule
  nsxt/resource_nsxt_firewall_section.go
  website/docs/r/firewall_section.html.markdown
Labels: documentation, size/XS

#159 And and acceptance test for edge FW
  nsxt/resource_nsxt_firewall_section.go
  nsxt/resource_nsxt_firewall_section_test.go
Labels: size/M
