Repository vmware/terraform-provider-nsxt, pull requests merged in 2019-10, with the labels that each got.

#191 fix refresh failures
  nsxt/resource_nsxt_algorithm_type_ns_service.go
  nsxt/resource_nsxt_dhcp_relay_profile.go
  nsxt/resource_nsxt_dhcp_relay_service.go
  nsxt/resource_nsxt_dhcp_server_ip_pool.go
  nsxt/resource_nsxt_dhcp_server_profile.go
  nsxt/resource_nsxt_ether_type_ns_service.go
  nsxt/resource_nsxt_firewall_section.go
  nsxt/resource_nsxt_icmp_type_ns_service.go
  nsxt/resource_nsxt_igmp_type_ns_service.go
  nsxt/resource_nsxt_ip_block.go
  nsxt/resource_nsxt_ip_block_subnet.go
  nsxt/resource_nsxt_ip_discovery_switching_profile.go
  nsxt/resource_nsxt_ip_pool.go
  nsxt/resource_nsxt_ip_protocol_ns_service.go
  nsxt/resource_nsxt_ip_set.go
  nsxt/resource_nsxt_l4_port_set_ns_service.go
  nsxt/resource_nsxt_lb_client_ssl_profile.go
  nsxt/resource_nsxt_lb_cookie_persistence_profile.go
  nsxt/resource_nsxt_lb_fast_tcp_application_profile.go
  nsxt/resource_nsxt_lb_fast_udp_application_profile.go
  nsxt/resource_nsxt_lb_http_application_profile.go
  nsxt/resource_nsxt_lb_http_forwarding_rule.go
  nsxt/resource_nsxt_lb_http_monitor.go
  nsxt/resource_nsxt_lb_http_request_rewrite_rule.go
  nsxt/resource_nsxt_lb_http_response_rewrite_rule.go
  nsxt/resource_nsxt_lb_http_virtual_server.go
  nsxt/resource_nsxt_lb_https_monitor.go
  nsxt/resource_nsxt_lb_icmp_monitor.go
  nsxt/resource_nsxt_lb_passive_monitor.go
  nsxt/resource_nsxt_lb_pool.go
  nsxt/resource_nsxt_lb_server_ssl_profile.go
  nsxt/resource_nsxt_lb_service.go
  nsxt/resource_nsxt_lb_source_ip_persistence_profile.go
  nsxt/resource_nsxt_lb_tcp_monitor.go
  nsxt/resource_nsxt_lb_tcp_virtual_server.go
  nsxt/resource_nsxt_lb_udp_monitor.go
  nsxt/resource_nsxt_lb_udp_virtual_server.go
  nsxt/resource_nsxt_logical_dhcp_port.go
  nsxt/resource_nsxt_logical_dhcp_server.go
  nsxt/resource_nsxt_logical_port.go
  nsxt/resource_nsxt_logical_router_centralized_service_port.go
  nsxt/resource_nsxt_logical_router_downlink_port.go
  nsxt/resource_nsxt_logical_router_link_port_on_tier0.go
  nsxt/resource_nsxt_logical_router_link_port_on_tier1.go
  nsxt/resource_nsxt_logical_switch.go
  nsxt/resource_nsxt_logical_tier0_router.go
  nsxt/resource_nsxt_logical_tier1_router.go
  nsxt/resource_nsxt_mac_management_switching_profile.go
  nsxt/resource_nsxt_ns_group.go
  nsxt/resource_nsxt_ns_service_group.go
  nsxt/resource_nsxt_qos_switching_profile.go
  nsxt/resource_nsxt_spoofguard_switching_profile.go
  nsxt/resource_nsxt_static_route.go
  nsxt/resource_nsxt_switch_security_switching_profile.go
  nsxt/resource_nsxt_vlan_logical_switch.go
Labels: size/XL

#190 Add resource nsxt_ip_pool_allocation_ip_address
  nsxt/data_source_nsxt_ip_pool.go
  nsxt/data_source_nsxt_ip_pool_test.go
  nsxt/provider.go
  nsxt/resource_nsxt_ip_pool_allocation_ip_address.go
  nsxt/resource_nsxt_ip_pool_allocation_ip_address_test.go
  nsxt/utils_test.go
  website/docs/d/ip_pool.html.markdown
  website/docs/r/ip_pool_allocation_ip_address.html.markdown
  website/nsxt.erb
Labels: documentation, size/XL

#196 fix for "Error during IPPoolAllocationIPAddress delete: EOF"
  nsxt/resource_nsxt_ip_pool_allocation_ip_address.go
Labels: size/XS

#193 Fix import crashes
  nsxt/resource_nsxt_logical_router_downlink_port.go
  nsxt/resource_nsxt_logical_router_link_port_on_tier1.go
Labels: size/XS

#194 Fix error handling in data sources
  nsxt/data_source_nsxt_certificate.go
  nsxt/data_source_nsxt_edge_cluster.go
  nsxt/data_source_nsxt_logical_tier0_router.go
  nsxt/data_source_nsxt_logical_tier1_router.go
  nsxt/data_source_nsxt_mac_pool.go
  nsxt/data_source_nsxt_ns_group.go
  nsxt/data_source_nsxt_ns_service.go
  nsxt/data_source_nsxt_switching_profile.go
  nsxt/data_source_nsxt_transport_zone.go
Labels: size/M

#195 Support IPSet type in ns group membership criteria
  nsxt/resource_nsxt_ip_set.go
  nsxt/resource_nsxt_ns_group.go
Labels: size/XS

#199 Improve documentation
  website/docs/r/ip_block.html.markdown
  website/docs/r/ip_block_subnet.html.markdown
  website/docs/r/lb_http_virtual_server.html.markdown
  website/docs/r/logical_switch.html.markdown
  website/docs/r/logical_tier1_router.html.markdown
  website/docs/r/vlan_logical_switch.html.markdown
Labels: documentation, size/XS
