Repository vmware/terraform-provider-nsxt, pull requests merged in 2019-02, with the labels that each got.

#132 Add remote_auth option for vIDM case
  nsxt/provider.go
  nsxt/provider_test.go
  nsxt/resource_nsxt_algorithm_type_ns_service_test.go
  vendor/github.com/vmware/go-vmware-nsxt/api_client.go
  vendor/github.com/vmware/go-vmware-nsxt/configuration.go
  vendor/vendor.json
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/S

#137 Fix ip block subnet test to match NSX 2.4
  nsxt/resource_nsxt_ip_block_subnet_test.go
Labels: size/XS

#136 Fix ICMP NS service tests
  nsxt/resource_nsxt_icmp_type_ns_service_test.go
Labels: size/XS

#138 Change lb http rule redirect status code
  nsxt/resource_nsxt_lb_http_forwarding_rule.go
  nsxt/resource_nsxt_lb_http_forwarding_rule_test.go
Labels: size/XS

#140 Fix ns group documentation
  website/docs/r/ns_group.html.markdown
Labels: documentation, size/XS

#139 Set router failover mode to default if absent
  nsxt/resource_nsxt_logical_tier1_router.go
Labels: size/XS

#142 Mark edge_cluster_id as ForceNew in T1 router
  nsxt/resource_nsxt_logical_tier1_router.go
Labels: size/XS

#143 Add doc details to lb http virtual server
  website/docs/r/lb_http_virtual_server.html.markdown
Labels: documentation, size/XS

#144 Update changelog
  CHANGELOG.md
Labels: size/S

#145 Remove MAXINT that fails builds on some platforms
  nsxt/resource_nsxt_dhcp_server_ip_pool.go
Labels: bug, size/XS

#146 Skip certain tests for old platform
  nsxt/resource_nsxt_lb_client_ssl_profile_test.go
  nsxt/resource_nsxt_lb_cookie_persistence_profile_test.go
  nsxt/resource_nsxt_lb_fast_tcp_application_profile_test.go
  nsxt/resource_nsxt_lb_fast_udp_application_profile_test.go
  nsxt/resource_nsxt_lb_http_application_profile_test.go
  nsxt/resource_nsxt_lb_http_forwarding_rule_test.go
  nsxt/resource_nsxt_lb_http_virtual_server_test.go
  nsxt/resource_nsxt_lb_icmp_monitor_test.go
  nsxt/resource_nsxt_lb_l4_monitor_test.go
  nsxt/resource_nsxt_lb_l7_monitor_test.go
  nsxt/resource_nsxt_lb_passive_monitor_test.go
  nsxt/resource_nsxt_lb_pool_test.go
  nsxt/resource_nsxt_lb_server_ssl_profile_test.go
  nsxt/resource_nsxt_logical_router_centralized_service_port_test.go
Labels: size/M
