Repository vmware/terraform-provider-nsxt, pull requests merged in 2019-03, with the labels that each got.

#148 Mark 2.3+ resources as such in docs
  website/docs/r/lb_client_ssl_profile.html.markdown
  website/docs/r/lb_cookie_persistence_profile.html.markdown
  website/docs/r/lb_fast_tcp_application_profile.html.markdown
  website/docs/r/lb_fast_udp_application_profile.html.markdown
  website/docs/r/lb_http_application_profile.html.markdown
  website/docs/r/lb_http_forwarding_rule.html.markdown
  website/docs/r/lb_http_monitor.html.markdown
  website/docs/r/lb_http_request_rewrite_rule.html.markdown
  website/docs/r/lb_http_response_rewrite_rule.html.markdown
  website/docs/r/lb_icmp_monitor.html.markdown
  website/docs/r/lb_passive_monitor.html.markdown
  website/docs/r/lb_pool.html.markdown
  website/docs/r/lb_server_ssl_profile.html.markdown
  website/docs/r/lb_service.html.markdown
  website/docs/r/lb_source_ip_persistence_profile.html.markdown
  website/docs/r/lb_tcp_monitor.html.markdown
  website/docs/r/lb_tcp_virtual_server.html.markdown
  website/docs/r/lb_udp_monitor.html.markdown
  website/docs/r/lb_udp_virtual_server.html.markdown
  website/docs/r/logical_router_centralized_service_port.html.markdown
Labels: documentation, size/S

#149 Add platform version clarification in README
  README.md
Labels: size/XS

#147 Removed extra ` from line 45 after }
  website/docs/r/lb_service.html.markdown
Labels: documentation, size/XS

#150 Add ability to control FW section
  nsxt/resource_nsxt_firewall_section.go
  nsxt/resource_nsxt_firewall_section_test.go
  website/docs/r/firewall_section.html.markdown
Labels: documentation, size/M

#154 Pass IDs for the FW sections and rules for update
  nsxt/resource_nsxt_firewall_section.go
Labels: size/XS

#156 Ignore order of services in FW rules
  nsxt/resource_nsxt_firewall_section.go
Labels: size/XS
