Repository vmware/terraform-provider-nsxt, pull requests merged in 2020-03, with the labels that each got.

#251 Mark scope as Computed in policy_nat_rule resource
  nsxt/resource_nsxt_policy_nat_rule.go
Labels: size/XS

#253 Allow non-default enforcement point in policy vm
  nsxt/policy_utils.go
  nsxt/resource_nsxt_policy_vm_tags.go
Labels: size/XS

#255 Add urpf_mode to policy gateway interface resource
  nsxt/policy_common.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
  nsxt/resource_nsxt_policy_tier1_gateway_interface.go
  nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go
  website/docs/r/policy_tier0_gateway_interface.html.markdown
  website/docs/r/policy_tier1_gateway_interface.html.markdown
Labels: documentation, size/M

#254 Add server_address in policy segment subnet dhcp
  nsxt/resource_nsxt_policy_dhcp_server.go
  nsxt/resource_nsxt_policy_segment_test.go
  nsxt/resource_nsxt_policy_vlan_segment_test.go
  nsxt/segment_common.go
  website/docs/r/policy_dhcp_server.html.markdown
  website/docs/r/policy_segment.html.markdown
  website/docs/r/policy_vlan_segment.html.markdown
Labels: documentation, size/M

#256 Expose pool_allocation and qos settings on Tier1
  nsxt/data_source_nsxt_policy_gateway_qos_profile.go
  nsxt/data_source_nsxt_policy_gateway_qos_profile_test.go
  nsxt/provider.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway_test.go
  website/docs/d/policy_gateway_qos_profile.html.markdown
  website/docs/r/policy_tier1_gateway.html.markdown
  website/nsxt.erb
Labels: documentation, size/XL

#258 Add data source for policy segment realization
  nsxt/data_source_nsxt_policy_realization_info_test.go
  nsxt/data_source_nsxt_policy_segment_realization.go
  nsxt/data_source_nsxt_policy_segment_realization_test.go
  nsxt/provider.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/ArpTableClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/ArpTableTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DefaultArpTableClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DefaultDhcpStaticBindingConfigsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DefaultPortsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DefaultSegmentDiscoveryProfileBindingMapsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DefaultSegmentMonitoringProfileBindingMapsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DefaultSegmentQosProfileBindingMapsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DefaultSegmentSecurityProfileBindingMapsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DefaultServiceSegmentsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DefaultStateClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DefaultStatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DhcpStaticBindingConfigsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/DhcpStaticBindingConfigsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/PortsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/PortsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/SegmentDiscoveryProfileBindingMapsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/SegmentDiscoveryProfileBindingMapsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/SegmentMonitoringProfileBindingMapsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/SegmentMonitoringProfileBindingMapsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/SegmentQosProfileBindingMapsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/SegmentQosProfileBindingMapsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/SegmentSecurityProfileBindingMapsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/SegmentSecurityProfileBindingMapsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/SegmentsPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/ServiceSegmentsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/ServiceSegmentsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/StateClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/StateTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/StatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/segments/StatisticsTypes.go
  vendor/modules.txt
  website/docs/d/policy_realization_info.html.markdown
  website/docs/d/policy_segment_realization.html.markdown
Labels: dependencies, documentation, size/XXL

#259 Use put instead of patch in segment update
  nsxt/data_source_nsxt_policy_segment_realization.go
  nsxt/resource_nsxt_policy_segment_test.go
  nsxt/segment_common.go
Labels: size/XS

#261 Optimize vm tag resources
  nsxt/resource_nsxt_policy_vm_tags.go
  nsxt/resource_nsxt_policy_vm_tags_test.go
  nsxt/resource_nsxt_vm_tags.go
  nsxt/utils.go
Labels: size/M

#262 Fix validation in policy vrf router
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier0_gateway_test.go
  nsxt/validators.go
Labels: size/M

#263 Update typo in title
  website/docs/d/certificate.html.markdown
Labels: documentation, size/XS

#264 Allow global-infra in policy path validation
  nsxt/policy_utils.go
Labels: size/XS

#265 Improve error handling in policy ds tests
  nsxt/data_source_nsxt_policy_gateway_qos_profile_test.go
  nsxt/data_source_nsxt_policy_ip_block_test.go
  nsxt/data_source_nsxt_policy_ip_discovery_profile_test.go
  nsxt/data_source_nsxt_policy_ip_pool_test.go
  nsxt/data_source_nsxt_policy_ipv6_dad_profile_test.go
  nsxt/data_source_nsxt_policy_lb_app_profile_test.go
  nsxt/data_source_nsxt_policy_lb_client_ssl_profile_test.go
  nsxt/data_source_nsxt_policy_lb_monitor_test.go
  nsxt/data_source_nsxt_policy_lb_server_ssl_profile_test.go
  nsxt/data_source_nsxt_policy_qos_profile_test.go
  nsxt/data_source_nsxt_policy_segment_security_profile_test.go
  nsxt/data_source_nsxt_policy_spoofguard_profile_test.go
  nsxt/data_source_nsxt_policy_tier0_gateway_test.go
  nsxt/data_source_nsxt_policy_tier1_gateway_test.go
  nsxt/data_source_nsxt_policy_vni_pool_test.go
Labels: size/M

#266 Enforce version checks in acceptance tests
  nsxt/data_source_nsxt_policy_gateway_qos_profile_test.go
  nsxt/data_source_nsxt_policy_ip_block_test.go
  nsxt/data_source_nsxt_policy_realization_info_test.go
  nsxt/data_source_nsxt_policy_segment_realization_test.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway_interface.go
  nsxt/resource_nsxt_policy_tier1_gateway_test.go
Labels: size/L

#267 Implement direct membership in policy group
  nsxt/resource_nsxt_policy_group.go
  nsxt/resource_nsxt_policy_group_test.go
  website/docs/r/policy_group.html.markdown
Labels: documentation, size/L

#269 Update document text and main example
  website/docs/index.html.markdown
Labels: documentation, size/XL

#270 Support teaming policy attribute in policy segment
  nsxt/segment_common.go
  website/docs/r/policy_segment.html.markdown
  website/docs/r/policy_vlan_segment.html.markdown
Labels: documentation, size/XS

#277 Update CHANGELOG in preparation for 2.0.0 release
  CHANGELOG.md
Labels: size/XS

#276 Fix and clarify policy documentation
  website/docs/r/policy_bgp_neighbor.html.markdown
  website/docs/r/policy_segment.html.markdown
  website/docs/r/policy_tier0_gateway.html.markdown
  website/docs/r/policy_vlan_segment.html.markdown
Labels: documentation, size/XS

#275 Disable VMC temporarily
  nsxt/provider.go
  website/docs/index.html.markdown
  website/docs/r/policy_gateway_policy.html.markdown
  website/docs/r/policy_group.html.markdown
  website/docs/r/policy_security_policy.html.markdown
Labels: documentation, size/S

#273 Fix policy bgp resource according to nsx changes
  nsxt/resource_nsxt_policy_bgp_neighbor.go
  nsxt/resource_nsxt_policy_bgp_neighbor_test.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier0_gateway_test.go
Labels: size/XS

#280 Update README ofr 2.0.0 release
  README.md
Labels: size/XS

#278 Rename old resources to Manager resources in doc
  website/nsxt.erb
Labels: documentation, size/L

#281 Documentation update
  website/docs/r/policy_gateway_policy.html.markdown
  website/docs/r/policy_nat_rule.html.markdown
  website/docs/r/policy_static_route.html.markdown
Labels: documentation, size/XS

#284 Add clarification in bgp doc
  website/docs/r/policy_bgp_neighbor.html.markdown
Labels: documentation, size/XS

#285 Fix 32-bit compilation
  nsxt/resource_nsxt_policy_dhcp_server.go
  nsxt/segment_common.go
Labels: size/XS
