Repository vmware/terraform-provider-nsxt, pull requests merged in 2020-07, with the labels that each got.

#381 A better way to assign client auth for policy
  nsxt/provider.go
Labels: size/XS

#380 Fix gateway documentation
  website/docs/r/policy_tier0_gateway.html.markdown
  website/docs/r/policy_tier0_gateway_interface.html.markdown
  website/docs/r/policy_tier1_gateway.html.markdown
Labels: documentation, size/XS

#379 Parallelize more acceptance tests
  nsxt/resource_nsxt_dhcp_relay_service_test.go
  nsxt/resource_nsxt_ip_block_test.go
  nsxt/resource_nsxt_ip_discovery_switching_profile_test.go
  nsxt/resource_nsxt_mac_management_switching_profile_test.go
  nsxt/resource_nsxt_ns_service_group_test.go
  nsxt/resource_nsxt_policy_dhcp_relay_test.go
  nsxt/resource_nsxt_policy_dhcp_server_test.go
  nsxt/resource_nsxt_qos_switching_profile_test.go
  nsxt/resource_nsxt_spoofguard_switching_profile_test.go
  nsxt/resource_nsxt_static_route_test.go
  nsxt/resource_nsxt_switch_security_switching_profile_test.go
  nsxt/resource_nsxt_vm_tags_test.go
Labels: size/M

#384 Segment profiles
  nsxt/policy_common.go
  nsxt/resource_nsxt_policy_segment_test.go
  nsxt/segment_common.go
  website/docs/r/policy_segment.html.markdown
  website/docs/r/policy_vlan_segment.html.markdown
Labels: documentation, size/XL

#382 Support GM Tier1 Interface
  nsxt/gateway_common.go
  nsxt/policy_common.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
  nsxt/resource_nsxt_policy_tier1_gateway_interface.go
  nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/DefaultFloodProtectionProfileBindingsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/DefaultGatewayFirewallClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/DefaultInterfacesClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/DefaultSessionTimerProfileBindingsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/FloodProtectionProfileBindingsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/FloodProtectionProfileBindingsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/GatewayFirewallClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/GatewayFirewallTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/InterfacesClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/InterfacesTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/LocaleServicesPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/SessionTimerProfileBindingsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/SessionTimerProfileBindingsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/ArpTableClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/ArpTableTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/DadStateClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/DadStateTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/DefaultArpTableClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/DefaultDadStateClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/DefaultStatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/InterfacesPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/StatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/StatisticsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/statistics/DefaultSummaryClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/statistics/StatisticsPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/statistics/SummaryClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/statistics/SummaryTypes.go
  website/docs/r/policy_tier0_gateway_interface.html.markdown
  website/docs/r/policy_tier1_gateway_interface.html.markdown
Labels: dependencies, documentation, size/XXL

#390 Fix TestAccResourceNsxtGlobalPolicySecurityPolicy_withSite
  nsxt/resource_nsxt_policy_security_policy_test.go
Labels: size/XS

#389 Avoid extra roundtrip for updating GW services
  nsxt/gateway_common.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier0_gateway_gm_test.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
Labels: size/M

#387 Fix route filters in bgp neighbor resource
  nsxt/resource_nsxt_policy_bgp_neighbor.go
Labels: size/XS

#386 Do not set nsx_id in gateway tests
  nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
  nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go
Labels: size/S

#388 Support MAC address criteria in policy group
  nsxt/resource_nsxt_policy_group.go
  nsxt/resource_nsxt_policy_group_test.go
  website/docs/r/policy_group.html.markdown
Labels: documentation, size/M

#392 Fix realization datasource name in doc
  website/docs/d/policy_realization_info.html.markdown
Labels: documentation, size/XS

#391 Fix GM security policies category in doc
  website/docs/r/policy_gateway_policy.html.markdown
  website/docs/r/policy_security_policy.html.markdown
Labels: documentation, size/XS

#393 Support policy gateway prefix lists
  nsxt/provider.go
  nsxt/resource_nsxt_policy_gateway_prefix_list.go
  nsxt/resource_nsxt_policy_gateway_prefix_list_test.go
  nsxt/resource_nsxt_policy_nat_rule.go
  website/docs/r/policy_gateway_prefix_list.html.markdown
  website/nsxt.erb
Labels: documentation, size/XL

#394 Paralellize segment, group and T1 tests
  nsxt/resource_nsxt_policy_gateway_policy_test.go
  nsxt/resource_nsxt_policy_group_test.go
  nsxt/resource_nsxt_policy_security_policy_test.go
  nsxt/resource_nsxt_policy_segment_test.go
  nsxt/resource_nsxt_policy_tier1_gateway_test.go
  nsxt/resource_nsxt_policy_vlan_segment_test.go
Labels: size/M

#401 Mark subnet as optional in segment docs
  website/docs/r/policy_segment.html.markdown
  website/docs/r/policy_vlan_segment.html.markdown
Labels: documentation, size/XS

#398 Add BGP neighbor test with prefix lists
  nsxt/resource_nsxt_policy_bgp_neighbor_test.go
Labels: size/M

#396 Expose T0 gbp config on GM as a resource
  nsxt/gateway_common.go
  nsxt/policy_utils.go
  nsxt/provider.go
  nsxt/resource_nsxt_policy_bgp_config.go
  nsxt/resource_nsxt_policy_bgp_config_test.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
  website/docs/r/policy_bgp_config.html.markdown
  website/docs/r/policy_tier0_gateway.html.markdown
  website/nsxt.erb
Labels: documentation, size/XL

#405 Support BGP AS in ASDot format
  nsxt/resource_nsxt_policy_bgp_config_test.go
  nsxt/resource_nsxt_policy_bgp_neighbor.go
  nsxt/resource_nsxt_policy_bgp_neighbor_test.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/validators.go
  website/docs/r/policy_bgp_neighbor.html.markdown
Labels: documentation, size/S

#403 Bgp neighbor support for GM
  nsxt/data_source_nsxt_policy_transport_zone_test.go
  nsxt/resource_nsxt_policy_bgp_neighbor.go
  nsxt/resource_nsxt_policy_bgp_neighbor_test.go
  nsxt/resource_nsxt_policy_segment_test.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
  nsxt/resource_nsxt_policy_vlan_segment_test.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/locale_services/bgp/BgpPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/locale_services/bgp/DefaultNeighborsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/locale_services/bgp/NeighborsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/locale_services/bgp/NeighborsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/ArpTableClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/ArpTableTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/DadStateClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/DadStateTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/DefaultArpTableClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/DefaultDadStateClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/DefaultStatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/InterfacesPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/StatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/StatisticsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/statistics/DefaultSummaryClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/statistics/SummaryClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/locale_services/interfaces/statistics/SummaryTypes.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#406 Support tagging VM segment port
  nsxt/policy_utils.go
  nsxt/resource_nsxt_policy_vm_tags.go
  nsxt/resource_nsxt_policy_vm_tags_test.go
  nsxt/utils_test.go
  website/docs/r/policy_vm_tags.html.markdown
Labels: documentation, size/XL

#407 Smallfix docs/r/policy_segment.html.markdown
  website/docs/r/policy_segment.html.markdown
Labels: documentation, size/XS

#408 Parallelize more tests to save test execution time
  nsxt/resource_nsxt_logical_router_centralized_service_port_test.go
  nsxt/resource_nsxt_logical_router_downlink_port_test.go
  nsxt/resource_nsxt_logical_router_link_port_on_tier0_test.go
  nsxt/resource_nsxt_logical_router_link_port_on_tier1_test.go
  nsxt/resource_nsxt_logical_tier1_router_test.go
  nsxt/resource_nsxt_nat_rule_test.go
  nsxt/resource_nsxt_policy_gateway_prefix_list_test.go
  nsxt/resource_nsxt_policy_ip_block_test.go
  nsxt/resource_nsxt_policy_ip_pool_static_subnet_test.go
  nsxt/resource_nsxt_policy_ip_pool_test.go
  nsxt/resource_nsxt_policy_lb_service_test.go
  nsxt/resource_nsxt_policy_nat_rule_test.go
  nsxt/resource_nsxt_policy_static_route_test.go
Labels: size/M

#410 Fix NAT test for GM
  nsxt/resource_nsxt_policy_nat_rule_test.go
Labels: size/XS
