Repository vmware/terraform-provider-nsxt, pull requests merged in 2020-06, with the labels that each got.

#330 Use double converter utility for GM objects
  nsxt/data_source_nsxt_policy_gateway_qos_profile_test.go
  nsxt/data_source_nsxt_policy_qos_profile_test.go
  nsxt/resource_nsxt_policy_service.go
Labels: size/M

#328 Support locale_service clause on GM tier0
  nsxt/policy_common.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface.go
  website/docs/r/policy_tier0_gateway.html.markdown
Labels: documentation, size/XL

#335 Switch to H-API in policy T1 Gateway
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway_interface.go
Labels: size/L

#334 GM support for Group
  nsxt/policy_common.go
  nsxt/resource_nsxt_policy_group.go
  nsxt/resource_nsxt_policy_group_test.go
  nsxt/utils_test.go
  website/docs/r/policy_group.html.markdown
Labels: documentation, size/XL

#337 Change GetOkExists to GetOk for non-bool arguments
  nsxt/data_source_nsxt_policy_edge_node.go
  nsxt/data_source_nsxt_policy_lb_app_profile.go
  nsxt/data_source_nsxt_policy_lb_monitor.go
  nsxt/data_source_nsxt_policy_lb_persistence_profile.go
  nsxt/segment_common.go
Labels: size/XS

#339 Add Global Manager support for Tier1
  nsxt/gateway_common.go
  nsxt/policy_common.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
  website/docs/r/policy_tier0_gateway.html.markdown
  website/docs/r/policy_tier1_gateway.html.markdown
Labels: documentation, size/XL

#333 Support GM edge cluster/node data sources
  nsxt/data_source_nsxt_policy_edge_cluster.go
  nsxt/data_source_nsxt_policy_edge_cluster_test.go
  nsxt/data_source_nsxt_policy_edge_node.go
  nsxt/data_source_nsxt_policy_edge_node_test.go
  nsxt/data_source_nsxt_policy_transport_zone_test.go
  nsxt/policy_gm_search.go
  nsxt/utils_test.go
  website/docs/d/policy_edge_cluster.html.markdown
  website/docs/d/policy_transport_zone.html.markdown
Labels: documentation, size/M

#332 Global manager realization data source
  nsxt/data_source_nsxt_policy_realization_info.go
  nsxt/data_source_nsxt_policy_realization_info_test.go
  nsxt/data_source_nsxt_policy_site_test.go
  nsxt/resource_nsxt_policy_service.go
  nsxt/utils_test.go
  website/docs/d/policy_realization_info.html.markdown
Labels: documentation, size/M

#345 fix test utils
  nsxt/resource_nsxt_policy_group_test.go
  nsxt/utils_test.go
Labels: size/XS

#342 Allow vlan range in policy vlan segments
  nsxt/resource_nsxt_policy_vlan_segment_test.go
  nsxt/segment_common.go
  nsxt/validators.go
  website/docs/r/policy_vlan_segment.html.markdown
Labels: documentation, size/S

#344 Gateway intersite
  nsxt/data_source_nsxt_policy_tier1_gateway_test.go
  nsxt/gateway_common.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier0_gateway_test.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway_test.go
  nsxt/utils_test.go
  website/docs/r/policy_gateway_policy.html.markdown
  website/docs/r/policy_tier0_gateway.html.markdown
  website/docs/r/policy_tier1_gateway.html.markdown
Labels: documentation, size/L

#341 Info page for VMConAWS
  website/docs/guides_vmc.html.markdown
Labels: documentation, size/S

#349 Add VMC documentation link on main page
  CHANGELOG.md
  website/nsxt.erb
Labels: documentation, size/XS

#351 Refactor LB service test to fix destroy issue
  nsxt/resource_nsxt_policy_lb_service_test.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
Labels: size/S

#350 Update CHANGELOG for 2.1.0 release
  CHANGELOG.md
Labels: size/XS

#343 GM Security Policy Support
  nsxt/resource_nsxt_policy_lb_service_test.go
  nsxt/resource_nsxt_policy_security_policy.go
  nsxt/resource_nsxt_policy_security_policy_test.go
  nsxt/utils_test.go
  website/docs/r/policy_security_policy.html.markdown
Labels: documentation, size/XL

#356 GM Gateway Policy Support
  nsxt/resource_nsxt_policy_gateway_policy.go
  nsxt/resource_nsxt_policy_gateway_policy_test.go
Labels: size/L

#354 Support GM segment & vlan segment resources
  nsxt/data_source_nsxt_policy_edge_cluster.go
  nsxt/data_source_nsxt_policy_realization_info.go
  nsxt/data_source_nsxt_policy_transport_zone.go
  nsxt/policy_common.go
  nsxt/resource_nsxt_policy_segment_test.go
  nsxt/resource_nsxt_policy_vlan_segment_test.go
  nsxt/segment_common.go
Labels: size/L

#359 Federation
  go.sum
  nsxt/data_source_nsxt_policy_edge_node.go
  nsxt/resource_nsxt_ip_pool_allocation_ip_address_test.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/utils_test.go
Labels: size/XS

#361 Fix GM tests execution
  nsxt/resource_nsxt_policy_tier0_gateway_gm_test.go
Labels: size/XS

#362 Fix edge node data source member index handling
  nsxt/data_source_nsxt_policy_edge_node.go
Labels: size/XS

#363 Support route redistribution config for T0
  nsxt/gateway_common.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier0_gateway_test.go
  website/docs/r/policy_tier0_gateway.html.markdown
Labels: documentation, size/L

#365 Fix some golint errors
  nsxt/policy_common.go
  nsxt/resource_nsxt_policy_security_policy_test.go
  nsxt/resource_nsxt_policy_segment_test.go
  nsxt/segment_common.go
Labels: size/S

#366 GM Nat Rule Support
  nsxt/policy_common.go
  nsxt/resource_nsxt_policy_nat_rule.go
  nsxt/resource_nsxt_policy_nat_rule_test.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/utils_test.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/DefaultNatRulesClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/DefaultStatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/NatPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/NatRulesClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/NatRulesTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/StatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/StatisticsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/nat_rules/DefaultStatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/nat_rules/NatRulesPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/nat_rules/StatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/nat_rules/StatisticsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/DefaultNatRulesClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/DefaultStatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/NatPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/NatRulesClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/NatRulesTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/StatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/StatisticsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/nat_rules/DefaultStatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/nat_rules/NatRulesPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/nat_rules/StatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/nat_rules/StatisticsTypes.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#367 Enable segment-related group test for GM
  nsxt/resource_nsxt_policy_group_test.go
Labels: size/XS

#368 Support T0 route redistribution for Global Manager
  nsxt/gateway_common.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier0_gateway_gm_test.go
Labels: size/XL

#369 Adjust global manager tests to testing topology
  nsxt/data_source_nsxt_policy_edge_cluster_test.go
  nsxt/data_source_nsxt_policy_tier1_gateway_test.go
  nsxt/data_source_nsxt_policy_transport_zone.go
  nsxt/data_source_nsxt_policy_transport_zone_test.go
  nsxt/resource_nsxt_policy_group_test.go
  nsxt/resource_nsxt_policy_segment_test.go
  nsxt/resource_nsxt_policy_vlan_segment_test.go
  nsxt/utils_test.go
Labels: size/M

#370 Fix global manager tests
  nsxt/data_source_nsxt_switching_profile_test.go
  nsxt/gateway_common.go
Labels: size/XS

#371 Paralellize some of resource tests
  nsxt/resource_nsxt_algorithm_type_ns_service_test.go
  nsxt/resource_nsxt_ether_type_ns_service_test.go
  nsxt/resource_nsxt_icmp_type_ns_service_test.go
  nsxt/resource_nsxt_igmp_type_ns_service_test.go
  nsxt/resource_nsxt_ip_protocol_ns_service_test.go
  nsxt/resource_nsxt_ip_set_test.go
  nsxt/resource_nsxt_l4_port_set_ns_service_test.go
  nsxt/resource_nsxt_lb_http_forwarding_rule_test.go
  nsxt/resource_nsxt_lb_http_request_rewrite_rule_test.go
  nsxt/resource_nsxt_lb_http_response_rewrite_rule_test.go
  nsxt/resource_nsxt_logical_switch_test.go
  nsxt/resource_nsxt_ns_group_test.go
  nsxt/resource_nsxt_policy_tier1_gateway_test.go
  nsxt/resource_nsxt_vlan_logical_switch_test.go
Labels: size/M

#372 Add context profile data source
  nsxt/data_source_nsxt_policy_context_profile.go
  nsxt/data_source_nsxt_policy_context_profile_test.go
  nsxt/provider.go
  website/docs/d/policy_context_profile.html.markdown
  website/nsxt.erb
Labels: documentation, size/L

#373 Support for AD in Group
  nsxt/resource_nsxt_policy_group.go
  nsxt/resource_nsxt_policy_group_test.go
  website/docs/r/policy_group.html.markdown
Labels: documentation, size/XL

#376 Fix error handling in Global Manager section
  nsxt/data_source_nsxt_policy_gateway_qos_profile_test.go
  nsxt/data_source_nsxt_policy_qos_profile_test.go
  nsxt/resource_nsxt_policy_service.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
  nsxt/segment_common.go
Labels: size/S

#377 Update vendor
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/nat_rules/DefaultStatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/nat_rules/NatRulesPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/nat_rules/StatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/nat/nat_rules/StatisticsTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/nat_rules/DefaultStatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/nat_rules/NatRulesPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/nat_rules/StatisticsClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/nat/nat_rules/StatisticsTypes.go
Labels: dependencies, size/XL

#375 Enable data source generator with global manager
  tools/data_source_nsxt_policy_template
  tools/data_source_nsxt_policy_test_template
Labels: size/M
