Repository vmware/terraform-provider-nsxt, pull requests merged in 2020-05, with the labels that each got.

#305 Verify null pointer check in policy read functions
  nsxt/resource_nsxt_policy_gateway_policy.go
  nsxt/resource_nsxt_policy_nat_rule.go
Labels: size/XS

#306 Update index.html.markdown
  website/docs/index.html.markdown
  website/docs/r/policy_segment.html.markdown
  website/docs/r/policy_tier0_gateway.html.markdown
  website/docs/r/policy_tier1_gateway.html.markdown
Labels: documentation, size/S

#308 Expose network_name in segment realization data
  nsxt/data_source_nsxt_policy_segment_realization.go
  nsxt/data_source_nsxt_policy_segment_realization_test.go
  website/docs/d/policy_segment_realization.html.markdown
Labels: documentation, size/XS

#311 Check for port existance on segment delete
  nsxt/data_source_nsxt_policy_segment_realization.go
  nsxt/segment_common.go
Labels: size/S

#314 Provider aliasing support
  nsxt/data_source_nsxt_policy_edge_cluster.go
  nsxt/data_source_nsxt_policy_edge_node.go
  nsxt/data_source_nsxt_policy_segment_realization.go
  nsxt/data_source_nsxt_policy_transport_zone.go
  nsxt/data_source_nsxt_policy_vm.go
  nsxt/policy_utils.go
  nsxt/provider.go
  nsxt/resource_nsxt_logical_switch.go
  nsxt/resource_nsxt_policy_vm_tags.go
  nsxt/resource_nsxt_policy_vm_tags_test.go
  nsxt/resource_nsxt_vlan_logical_switch.go
Labels: size/M

#310 Tier0intfip
  nsxt/resource_nsxt_policy_bgp_neighbor_test.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
  website/docs/r/policy_bgp_neighbor.html.markdown
  website/docs/r/policy_tier0_gateway_interface.html.markdown
Labels: documentation, size/M

#316 Add provider flag for a policy global manager env
  nsxt/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#318 Add global manager site data source
  nsxt/data_source_nsxt_policy_site.go
  nsxt/data_source_nsxt_policy_site_test.go
  nsxt/policy_common.go
  nsxt/policy_gm_search.go
  nsxt/provider.go
  nsxt/segment_common.go
  nsxt/utils_test.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/model/ModelPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/search/DefaultDslClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/search/DefaultQueryClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/search/DslClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/search/DslTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/search/QueryClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/search/QueryTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/search/SearchPackageTypes.go
  vendor/modules.txt
  website/docs/d/policy_site.html.markdown
  website/nsxt.erb
Labels: dependencies, documentation, size/XXL

#319 Add correct importer for ip pool allocation resource
  nsxt/data_source_nsxt_ip_pool.go
  nsxt/resource_nsxt_ip_pool_allocation_ip_address.go
  nsxt/resource_nsxt_ip_pool_allocation_ip_address_test.go
  website/docs/r/ip_pool_allocation_ip_address.html.markdown
Labels: documentation, size/M

#321 Fix policy segment delete error reporting
  nsxt/resource_nsxt_policy_service.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
Labels: size/XS

#322 Refactor resource existance detection helper
  nsxt/policy_utils.go
  nsxt/resource_nsxt_policy_dhcp_relay.go
  nsxt/resource_nsxt_policy_dhcp_server.go
  nsxt/resource_nsxt_policy_gateway_policy.go
  nsxt/resource_nsxt_policy_group.go
  nsxt/resource_nsxt_policy_ip_address_allocation.go
  nsxt/resource_nsxt_policy_ip_address_allocation_test.go
  nsxt/resource_nsxt_policy_ip_block.go
  nsxt/resource_nsxt_policy_ip_pool.go
  nsxt/resource_nsxt_policy_lb_pool.go
  nsxt/resource_nsxt_policy_lb_service.go
  nsxt/resource_nsxt_policy_lb_virtual_server.go
  nsxt/resource_nsxt_policy_security_policy.go
  nsxt/resource_nsxt_policy_service.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
  nsxt/segment_common.go
Labels: size/M

#320 GM switching profile & GW profile & service data sources
  nsxt/data_source_nsxt_policy_gateway_qos_profile.go
  nsxt/data_source_nsxt_policy_gateway_qos_profile_test.go
  nsxt/data_source_nsxt_policy_ip_discovery_profile.go
  nsxt/data_source_nsxt_policy_ip_discovery_profile_test.go
  nsxt/data_source_nsxt_policy_mac_discovery_profile.go
  nsxt/data_source_nsxt_policy_mac_discovery_profile_test.go
  nsxt/data_source_nsxt_policy_qos_profile.go
  nsxt/data_source_nsxt_policy_qos_profile_test.go
  nsxt/data_source_nsxt_policy_segment_security_profile.go
  nsxt/data_source_nsxt_policy_segment_security_profile_test.go
  nsxt/data_source_nsxt_policy_service.go
  nsxt/data_source_nsxt_policy_spoofguard_profile.go
  nsxt/data_source_nsxt_policy_spoofguard_profile_test.go
  nsxt/utils_test.go
Labels: size/XL

#324 Basic support for Tier0 on global manager
  nsxt/policy_utils.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
Labels: size/M

#323 GM service support as resource
  nsxt/resource_nsxt_policy_service.go
  nsxt/resource_nsxt_policy_service_test.go
Labels: size/M

#327 Federation transportzone support
  nsxt/data_source_nsxt_policy_gateway_qos_profile.go
  nsxt/data_source_nsxt_policy_ip_discovery_profile.go
  nsxt/data_source_nsxt_policy_mac_discovery_profile.go
  nsxt/data_source_nsxt_policy_qos_profile.go
  nsxt/data_source_nsxt_policy_segment_security_profile.go
  nsxt/data_source_nsxt_policy_service.go
  nsxt/data_source_nsxt_policy_site.go
  nsxt/data_source_nsxt_policy_spoofguard_profile.go
  nsxt/data_source_nsxt_policy_transport_zone.go
  nsxt/data_source_nsxt_policy_transport_zone_test.go
  nsxt/policy_common.go
  nsxt/policy_gm_search.go
  nsxt/provider.go
  nsxt/utils_test.go
  website/docs/d/policy_site.html.markdown
  website/docs/d/policy_transport_zone.html.markdown
Labels: documentation, size/L

#329 Tz doc
  website/docs/d/policy_transport_zone.html.markdown
Labels: documentation, size/XS
