Repository vmware/terraform-provider-nsxt, pull requests merged in 2020-08, with the labels that each got.

#411 Refactor policy lb pool tests to allow parallelism
  nsxt/resource_nsxt_policy_ip_address_allocation_test.go
  nsxt/resource_nsxt_policy_ip_pool_block_subnet_test.go
  nsxt/resource_nsxt_policy_ip_pool_static_subnet_test.go
  nsxt/resource_nsxt_policy_ip_pool_test.go
Labels: size/M

#400 Context profile
  nsxt/provider.go
  nsxt/resource_nsxt_policy_context_profile.go
  nsxt/resource_nsxt_policy_context_profile_test.go
  nsxt/utils.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/context_profiles/AttributesClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/context_profiles/AttributesTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/context_profiles/ContextProfilesPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/context_profiles/DefaultAttributesClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/context_profiles/AttributesClient.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/context_profiles/AttributesTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/context_profiles/ContextProfilesPackageTypes.go
  vendor/github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/context_profiles/DefaultAttributesClient.go
  website/docs/r/policy_context_profile.html.markdown
Labels: dependencies, documentation, size/XXL

#413 Improve hostname validation in provider
  nsxt/provider.go
  nsxt/validators.go
Labels: size/XS

#417 Fix T0 GM tests following backend changes
  nsxt/resource_nsxt_policy_tier0_gateway_gm_test.go
Labels: size/S

#415 Cont prof
  nsxt/resource_nsxt_policy_security_policy_test.go
Labels: size/M

#419 Revert "Avoid extra roundtrip for updating GW services" for HA_vip support
  nsxt/gateway_common.go
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
Labels: size/XS

#421 Fix Tier1 gateway interface doc header
  website/docs/r/policy_tier1_gateway_interface.html.markdown
Labels: documentation, size/XS

#425 Add prefix list in BGP neighbor doc example
  website/docs/r/policy_bgp_neighbor.html.markdown
Labels: documentation, size/XS

#422 Set Tier0 locale services as mandatory for GM
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier0_gateway_gm_test.go
  nsxt/resource_nsxt_policy_tier0_gateway_test.go
  website/docs/r/policy_tier0_gateway.html.markdown
Labels: documentation, size/S
