Repository vmware/terraform-provider-nsxt, pull requests merged in 2020-04, with the labels that each got.

#286 Re-enable VMC
  nsxt/provider.go
  website/docs/index.html.markdown
  website/docs/r/policy_gateway_policy.html.markdown
  website/docs/r/policy_group.html.markdown
  website/docs/r/policy_security_policy.html.markdown
Labels: documentation, size/M

#287 Fix vlan segment doc
  website/docs/r/policy_vlan_segment.html.markdown
Labels: documentation, size/XS

#288 Fix policy group read function
  nsxt/resource_nsxt_policy_group.go
Labels: size/S

#290 XLARGE LB service supported only since NSX 3
  nsxt/resource_nsxt_policy_lb_service.go
  website/docs/r/policy_lb_service.html.markdown
Labels: documentation, size/XS

#291 Fix list attributes in segment read action
  nsxt/segment_common.go
Labels: size/XS

#292 Fix client auth in policy resources
  nsxt/provider.go
Labels: size/XS

#293 Remove provider connectivity check
  nsxt/provider.go
  nsxt/utils.go
Labels: size/S

#294 Source network should not be mandatory for policy NAT rules
  nsxt/resource_nsxt_policy_nat_rule.go
Labels: size/XS

#299 Fix security policy import
  nsxt/resource_nsxt_policy_security_policy.go
Labels: size/XS

#300 Fix locale services with policy gateway interfaces
  nsxt/resource_nsxt_policy_tier0_gateway_interface.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
  nsxt/resource_nsxt_policy_tier1_gateway_interface.go
  nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go
Labels: size/S

#301 Fix Tier0 sub resources tags handling
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier0_gateway_test.go
Labels: size/S

#298 Add the correct type of security policy rule tag
  nsxt/policy_common.go
  nsxt/resource_nsxt_policy_gateway_policy_test.go
  nsxt/resource_nsxt_policy_security_policy_test.go
  website/docs/r/policy_gateway_policy.html.markdown
  website/docs/r/policy_security_policy.html.markdown
Labels: documentation, size/M

#303 Update with note on 3.0.0 compatibility of DHCP
  website/docs/index.html.markdown
Labels: documentation, size/XS

#302 Support remote auth for policy resources
  nsxt/provider.go
Labels: size/XS

#304 Allow Vlan Id 0 in Validator
  nsxt/validators.go
Labels: bug, good first issue, size/XS
