Repository vmware/terraform-provider-nsxt, pull requests merged in 2020-02, with the labels that each got.

#218 Add firewall section data source
  nsxt/data_source_nsxt_firewall_section.go
  nsxt/data_source_nsxt_firewall_section_test.go
  nsxt/provider.go
  website/docs/d/firewall_section.html.markdown
  website/docs/r/firewall_section.html.markdown
  website/nsxt.erb
Labels: documentation, size/L

#217 Expose enforcement point argument on provider
  nsxt/data_source_nsxt_policy_edge_cluster.go
  nsxt/data_source_nsxt_policy_edge_node.go
  nsxt/data_source_nsxt_policy_transport_zone.go
  nsxt/data_source_nsxt_policy_transport_zone_test.go
  nsxt/policy_common.go
  nsxt/provider.go
  nsxt/resource_nsxt_policy_vm_tags.go
  website/docs/d/policy_transport_zone.html.markdown
  website/docs/index.html.markdown
Labels: documentation, size/M

#223 Update doc for dhcp_ranges
  website/docs/r/policy_segment.html.markdown
  website/docs/r/policy_vlan_segment.html.markdown
Labels: documentation, size/XS

#220 Improve policy data source error handling
  nsxt/data_source_nsxt_policy_certificate.go
  nsxt/data_source_nsxt_policy_edge_cluster.go
  nsxt/data_source_nsxt_policy_edge_node.go
  nsxt/data_source_nsxt_policy_ip_discovery_profile.go
  nsxt/data_source_nsxt_policy_ip_discovery_profile_test.go
  nsxt/data_source_nsxt_policy_ipv6_dad_profile.go
  nsxt/data_source_nsxt_policy_ipv6_dad_profile_test.go
  nsxt/data_source_nsxt_policy_ipv6_ndra_profile.go
  nsxt/data_source_nsxt_policy_ipv6_ndra_profile_test.go
  nsxt/data_source_nsxt_policy_lb_app_profile.go
  nsxt/data_source_nsxt_policy_lb_app_profile_test.go
  nsxt/data_source_nsxt_policy_lb_client_ssl_profile.go
  nsxt/data_source_nsxt_policy_lb_client_ssl_profile_test.go
  nsxt/data_source_nsxt_policy_lb_monitor.go
  nsxt/data_source_nsxt_policy_lb_monitor_test.go
  nsxt/data_source_nsxt_policy_lb_persistence_profile.go
  nsxt/data_source_nsxt_policy_lb_server_ssl_profile.go
  nsxt/data_source_nsxt_policy_mac_discovery_profile.go
  nsxt/data_source_nsxt_policy_mac_discovery_profile_test.go
  nsxt/data_source_nsxt_policy_qos_profile.go
  nsxt/data_source_nsxt_policy_segment_security_profile.go
  nsxt/data_source_nsxt_policy_segment_security_profile_test.go
  nsxt/data_source_nsxt_policy_service.go
  nsxt/data_source_nsxt_policy_spoofguard_profile.go
  nsxt/data_source_nsxt_policy_spoofguard_profile_test.go
  nsxt/data_source_nsxt_policy_tier0_gateway.go
  nsxt/data_source_nsxt_policy_tier0_gateway_test.go
  nsxt/data_source_nsxt_policy_tier1_gateway.go
  nsxt/data_source_nsxt_policy_tier1_gateway_test.go
  nsxt/data_source_nsxt_policy_transport_zone.go
  nsxt/policy_errors.go
  nsxt/resource_nsxt_policy_lb_pool.go
Labels: size/L

#224 Policy block subnet - wait for delete realization
  nsxt/resource_nsxt_policy_ip_pool_block_subnet.go
  nsxt/resource_nsxt_policy_ip_pool_block_subnet_test.go
Labels: size/S

#228 Fix error handling
  nsxt/policy_errors.go
  nsxt/resource_nsxt_policy_ip_pool_block_subnet.go
Labels: size/XS

#229 added proxy support
  nsxt/provider.go
  nsxt/provider_test.go
Labels: size/XS

#232 Add policy IPAM data sources
  nsxt/data_source_nsxt_policy_ip_block.go
  nsxt/data_source_nsxt_policy_ip_block_test.go
  nsxt/data_source_nsxt_policy_ip_pool.go
  nsxt/data_source_nsxt_policy_ip_pool_test.go
  nsxt/provider.go
  website/docs/d/policy_ip_block.html.markdown
  website/docs/d/policy_ip_pool.html.markdown
  website/nsxt.erb
Labels: documentation, size/XL

#230 Add default value in policy_nat_rule
  nsxt/resource_nsxt_policy_nat_rule.go
Labels: size/XS

#235 Apply logical_port_tags to all VM ports
  nsxt/resource_nsxt_vm_tags.go
  website/docs/r/vm_tags.html.markdown
Labels: documentation, size/S

#240 Fix tag removal in vm tags resource
  nsxt/utils.go
Labels: size/XS

#238 Improve error report when error conversion fails
  nsxt/policy_errors.go
Labels: size/M

#239 Re-apply detach fix for logical switch resource
  nsxt/resource_nsxt_logical_switch.go
Labels: size/XS

#243 Fix creation of Tier0 with bgp config
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier0_gateway_test.go
  website/docs/r/policy_group.html.markdown
Labels: documentation, size/S

#244 Allow loopback T0 interface and fix VRF acc tests
  nsxt/data_source_nsxt_policy_realization_info_test.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface.go
  nsxt/resource_nsxt_policy_tier0_gateway_interface_test.go
  nsxt/resource_nsxt_policy_tier0_gateway_test.go
  nsxt/resource_nsxt_policy_tier1_gateway_interface_test.go
Labels: size/M

#245 Allow to configure dhcp server without gw
  nsxt/resource_nsxt_logical_dhcp_server.go
  nsxt/resource_nsxt_logical_dhcp_server_test.go
  website/docs/r/logical_dhcp_server.html.markdown
Labels: documentation, size/XS

#247 Mark snat as Computed in policy lb pool
  nsxt/resource_nsxt_policy_lb_pool.go
Labels: size/M

#246 Several documentation fixes for policy resources
  website/docs/r/policy_lb_virtual_server.html.markdown
  website/docs/r/policy_segment.html.markdown
  website/docs/r/policy_tier0_gateway.html.markdown
  website/docs/r/policy_tier0_gateway_interface.html.markdown
Labels: documentation, size/XS
