Repository vmware/terraform-provider-nsxt, pull requests merged in 2020-01, with the labels that each got.

#207 Upgrade sdk version to incorporate client auth fix
  go.mod
  go.sum
Labels: size/M

#211 skip TestAccDataSourceNsxtPolicyVM_basic without env var
  nsxt/data_source_nsxt_policy_vm_test.go
Labels: size/XS

#212 Remove unneeded attribute in policy vm data source
  nsxt/data_source_nsxt_policy_vm.go
  website/docs/d/policy_vm.html.markdown
Labels: documentation, size/XS

#214 Fix edge cluster assignment in gateways
  nsxt/resource_nsxt_policy_tier0_gateway.go
  nsxt/resource_nsxt_policy_tier1_gateway.go
Labels: size/XS

#216 Documentation fixes
  website/docs/d/policy_realization_info.html.markdown
  website/docs/r/policy_lb_pool.html.markdown
  website/docs/r/policy_tier0_gateway.html.markdown
  website/docs/r/policy_tier1_gateway.html.markdown
Labels: documentation, size/XS

#215 Improve policy service validation
  nsxt/resource_nsxt_policy_service.go
Labels: size/XS
